### ISSUE TITLE
crash on startup specifically on dedicated server

### ISSUE THREAD

**Issue by abudq** [Globox1997/SpoiledZ#16]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.6

### Mod Version

1.0.9

### Describe the Issue

crash on start up server with fabric seasons and spoiledz installed

### latest.log

https://gist.github.com/abudq/46f6c2ed62196932f655b752e2be0e26

### Do you use any other mods except the required ones?

no

**Comment by Linguardium** [comment]
simple enough fix. just need to pass a `this` reference when calling getCurrentSeason
https://github.com/Globox1997/SpoiledZ/blob/373049e6c6e0a62d0501f22432a1da844df92f17/src/main/java/net/spoiledz/mixin/ServerWorldMixin.java#L63-L77

https://github.com/lucaargolo/fabric-seasons/blob/ed49f84b889c398d884f7d26d7b519aac6155c64/src/main/java/io/github/lucaargolo/seasons/FabricSeasons.java#L226

**Comment by Globox1997** [comment]
Thanks Linguardium for the hint, source code of Seasons even says the method is for client side only, don't know how I missed that.
Fixed with [https://github.com/Globox1997/SpoiledZ/commit/495db3cbe6b3a05507f342a44f7bc52e3b1be222](https://github.com/Globox1997/SpoiledZ/commit/495db3cbe6b3a05507f342a44f7bc52e3b1be222)
